CREATE DATABASE IF NOT EXISTS `tecken` DEFAULT CHARACTER SET latin1 COLLATE  latin1_swedish_ci;
CREATE TABLE `users` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `bio` TEXT NOT NULL,
    CONSTRAINT id_pk PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;